### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by ptbello** [ptbello/_slated#3]
Hi  @naokomc, @Satojii, @gatespace do you have a japanese translation of _s?
(see https://github.com/Automattic/_s/issues/726 for context)
If so it would be wonderful if you could take a few minutes to refresh it and post a pr here
どうもありがとうございました!

**Comment by gatespace** [comment]
@ptbello 
I have japanese translation files.
see : https://github.com/gatespace/_s/tree/ja

**Comment by ptbello** [comment]
Hi @gatespace, wonderful! Can you fork this repo, refresh the translation and submit a pr?

**Comment by gatespace** [comment]
> Can you fork this repo, refresh the translation and submit a pr?

OK.
Please a few days because I get ready.

**Comment by ptbello** [comment]
Fine! Looking forward to your addition.

**Comment by gatespace** [comment]
I send PR.
see https://github.com/ptbello/_slated/pull/12

**Comment by ptbello** [comment]
Thanks for a great addition! I have update the readme to include your contribution.
