### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by ptbello** [ptbello/_slated#4]
Hi @glueckpress, @2ndkauboy, @Zodiac1978 mentioned here https://github.com/Automattic/_s/issues/726#issuecomment-97584821 you have a german translation.
It would be wonderful if you could take a few minutes to post a pr here.
Herzlichen Dank!

**Comment by glueckpress** [comment]
:+1: thx @2ndkauboy, and thx @ptbello for curating this repo. Way to go!
